---
name: Apache2-AuthenNIS
version: 0.14
author:
  - 'Nguon Hao Ching <hao@iteaha.us>'
abstract: mod_perl2 NIS Authentication module
license: perl
resources:
  license: http://dev.perl.org/licenses/
requires:
  Net::NIS: 0
  mod_perl2: 0
build_requires:
  Test::More: 0
provides:
  Apache2::AuthenNIS:
    file: lib/Apache2/AuthenNIS.pm
    version: 0.14
generated_by: Module::Build version 0.2808
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.2.html
  version: 1.2
